spring:
  application:
    name: kafka.bitrix
  main.banner:
    banner-mode: log
    location: classpath:/banner.txt
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: db
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        request.timeout.ms: 30000
        connections.max.idle.ms: 30000
    properties:
      security:
        protocol: PLAINTEXT
  datasource:
    url: jdbc:sqlserver://${DB_HOST}:1433;databaseName=PRUEBAS;encrypt=true;trustServerCertificate=true;
    username: KafkaService
    password: FIUkSfkwE90TzdsgjmtJ
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.apache.kafka: INFO
    org.apache.hc.client5.http: OFF

rest:
  bitrix:
    port: 80
    hostname: sierrasyequipos.bitrix24.co
    url: https://sierrasyequipos.bitrix24.co/rest/${BITRIX_USER}/${BITRIX_TOKEN}/