spring:
  application:
    name: kafka.bitrix
  main.banner:
    banner-mode: log
    location: classpath:/banner.txt
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: db

server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: INFO


rest:
  bitrix:
    port: 80
    hostname: sierrasyequipos.bitrix24.co
    url: https://sierrasyequipos.bitrix24.co/rest/3614/${BITRIX_TOKEN}/