spring:
  application:
    name: kafka.bitrix
  main.banner:
    banner-mode: log
    location: classpath:/banner.txt
  jackson:
    default-property-inclusion: non_null
    time-zone: America/Bogota
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: db-spring
      auto-offset-reset: latest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        request.timeout.ms: 30000
        connections.max.idle.ms: 30000
    properties:
      security:
        protocol: PLAINTEXT
  datasource:
    url: jdbc:sqlserver://${DB_HOST}:1433;databaseName=${DATABASE};encrypt=true;trustServerCertificate=true;
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        jdbc.time_zone: America/Bogota

management.endpoint.health.enabled: true
management.endpoints.web.exposure.include: health

server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.apache.kafka: INFO
    org.apache.hc.client5.http: OFF
  file:
    name: /bitrix/logs/app.log

rest:
  bitrix:
    port: 80
    hostname: sierrasyequipos.bitrix24.co
    url: https://sierrasyequipos.bitrix24.co/rest/${BITRIX_USER}/${BITRIX_TOKEN}/
  migration:
    url: http://192.168.3.11:9000/